import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import poolsRouter from "./pools";
import transactionsRouter from "./transactions";
import winnersRouter from "./winners";
import adminRouter from "./admin";
import reviewsRouter from "./reviews";
import notificationsRouter from "./notifications";
import stakingRouter from "./staking";
import statsRouter from "./stats";
import userWalletRouter from "./userWallet";
import activityRouter from "./activity";
import referralRouter from "./referral";
import p2pRouter from "./p2p";
import cashoutArenaRouter from "./cashout-arena";
import scratchCardRouter from "./scratch-card";
import simulationRouter from "./simulation";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/stats", statsRouter);
router.use("/activity", activityRouter);
router.use("/auth", authRouter);
router.use("/user", userWalletRouter);
router.use("/users", usersRouter);
router.use("/pools", poolsRouter);
router.use("/transactions", transactionsRouter);
router.use("/staking", stakingRouter);
router.use("/referral", referralRouter);
router.use("/winners", winnersRouter);
router.use("/dashboard", adminRouter);
router.use("/admin", adminRouter);
router.use("/reviews", reviewsRouter);
router.use("/notifications", notificationsRouter);
router.use("/p2p", p2pRouter);
router.use("/cashout-arena", cashoutArenaRouter);
router.use("/scratch-card", scratchCardRouter);
router.use("/simulation", simulationRouter);

export default router;
